#!/usr/bin/env python3
"""Generate Homebrew and AUR definitions from qualified release payloads."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

TARGETS = (
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
)
VERSION = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
DESCRIPTION = "KNX monitor with CLI, TUI, GUI, REST and MCP"
REPOSITORY = "metaneutrons/devknx"
HOMEPAGE = f"https://github.com/{REPOSITORY}"


def digest(path: pathlib.Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def generate(
    version: str, tag: str, payload_dir: pathlib.Path, output_dir: pathlib.Path
) -> tuple[pathlib.Path, ...]:
    if not VERSION.fullmatch(version) or not re.fullmatch(
        rf"v{re.escape(version)}(?:-[0-9A-Za-z.-]+)?", tag
    ):
        raise ValueError("tag and core version do not agree")
    names = {
        target: f"devknx-{tag}-{target}.tar.gz" for target in TARGETS
    }
    app = f"devknx-{tag}-aarch64-apple-darwin.app.zip"
    source_archive = f"devknx-{tag}-source.tar.gz"
    for name in (*names.values(), app, source_archive):
        path = payload_dir / name
        if not path.is_file() or not path.stat().st_size:
            raise ValueError(f"missing qualified payload: {path}")
    sha = {target: digest(payload_dir / name) for target, name in names.items()}
    app_sha = digest(payload_dir / app)
    source_sha = digest(payload_dir / source_archive)
    base = f"{HOMEPAGE}/releases/download/{tag}"
    output_dir.mkdir(parents=True, exist_ok=True)

    formula = output_dir / "devknx.rb"
    cask = output_dir / "devknx-app.rb"
    binary = output_dir / "devknx-bin.PKGBUILD"
    source = output_dir / "devknx.PKGBUILD"
    for path in (formula, cask, binary, source):
        if path.exists():
            raise ValueError(f"refusing to overwrite {path}")

    formula.write_text(
        f'''# typed: strict
# frozen_string_literal: true

# Generated by scripts/release/package_metadata.py. Do not edit.
class Devknx < Formula
  desc "{DESCRIPTION}"
  homepage "{HOMEPAGE}"
  license "GPL-3.0-only"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "{base}/{names["aarch64-apple-darwin"]}"
      sha256 "{sha["aarch64-apple-darwin"]}"
    end
  end

  on_linux do
    depends_on "libx11"
    depends_on "libxcb"
    depends_on "libxkbcommon"
    depends_on "mesa"
    depends_on "wayland"
    if Hardware::CPU.arm?
      url "{base}/{names["aarch64-unknown-linux-gnu"]}"
      sha256 "{sha["aarch64-unknown-linux-gnu"]}"
    else
      url "{base}/{names["x86_64-unknown-linux-gnu"]}"
      sha256 "{sha["x86_64-unknown-linux-gnu"]}"
    end
  end

  def install
    root = Dir["devknx", "devknx-v*-*/devknx"].find {{ |path| File.file?(path) }}
    raise "missing devknx executable" unless root

    if OS.linux?
      libexec.install root
      gui_libraries = %w[libx11 libxcb libxkbcommon mesa wayland].map {{ |name| formula_opt_lib(name) }}
      loader_path = "#{{gui_libraries.join(":")}}${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
      bin.join("devknx").write_env_script libexec/"devknx", LD_LIBRARY_PATH: loader_path
    else
      bin.install root
    end
    source_root = File.dirname(root)
    doc.install File.join(source_root, "THIRD-PARTY-NOTICES.md")
    doc.install File.join(source_root, "licenses")
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/devknx --version")
  end
end
''',
        encoding="utf-8",
    )
    cask.write_text(
        f'''# typed: strict
# frozen_string_literal: true

# Generated by scripts/release/package_metadata.py. Do not edit.
cask "devknx-app" do
  version "{version}"
  sha256 "{app_sha}"

  url "{base}/{app}"
  name "devknx"
  desc "{DESCRIPTION}"
  homepage "{HOMEPAGE}"

  depends_on :macos

  app "devknx.app"

  caveats <<~EOS
    The command line tool is a separate package:
      brew install metaneutrons/tap/devknx
  EOS
end
''',
        encoding="utf-8",
    )
    binary.write_text(
        f'''# Generated by scripts/release/package_metadata.py. Do not edit.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=devknx-bin
pkgver={version}
pkgrel=1
pkgdesc='{DESCRIPTION}'
arch=('x86_64' 'aarch64')
url='{HOMEPAGE}'
license=('GPL-3.0-only')
depends=('glibc' 'gcc-libs' 'libxkbcommon' 'libx11' 'wayland' 'libgl')
provides=('devknx')
conflicts=('devknx')
options=('!strip' '!debug')
source_x86_64=('{base}/{names["x86_64-unknown-linux-gnu"]}')
sha256sums_x86_64=('{sha["x86_64-unknown-linux-gnu"]}')
source_aarch64=('{base}/{names["aarch64-unknown-linux-gnu"]}')
sha256sums_aarch64=('{sha["aarch64-unknown-linux-gnu"]}')

package() {{
  local target
  case "$CARCH" in
    x86_64) target=x86_64-unknown-linux-gnu ;;
    aarch64) target=aarch64-unknown-linux-gnu ;;
    *) return 1 ;;
  esac
  local root="$srcdir/devknx-{tag}-$target"
  install -Dm755 "$root/devknx" "$pkgdir/usr/bin/devknx"
  install -Dm644 "$root/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  install -Dm644 "$root/THIRD-PARTY-NOTICES.md" \
    "$pkgdir/usr/share/licenses/$pkgname/THIRD-PARTY-NOTICES.md"
  install -Dm644 -t "$pkgdir/usr/share/licenses/$pkgname/" "$root"/licenses/*
}}
''',
        encoding="utf-8",
    )
    source.write_text(
        f'''# Generated by scripts/release/package_metadata.py. Do not edit.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=devknx
pkgver={version}
pkgrel=1
pkgdesc='{DESCRIPTION}'
arch=('x86_64' 'aarch64')
url='{HOMEPAGE}'
license=('GPL-3.0-only')
depends=('gcc-libs' 'glibc' 'libxkbcommon' 'libx11' 'wayland' 'libgl')
makedepends=('cargo' 'git' 'libxcb')
conflicts=('devknx-bin')
options=('!lto' '!debug')
source=("{base}/{source_archive}")
sha256sums=('{source_sha}')
_srcdir="devknx-{tag}"

prepare() {{
  cd "$srcdir/$_srcdir"
  cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
}}

build() {{
  cd "$srcdir/$_srcdir"
  export CARGO_TARGET_DIR=target
  cargo build --frozen --release --no-default-features --features full
}}

check() {{
  cd "$srcdir/$_srcdir"
  export CARGO_TARGET_DIR=target
  cargo test --frozen --no-default-features --features full
}}

package() {{
  cd "$srcdir/$_srcdir"
  install -Dm755 target/release/devknx "$pkgdir/usr/bin/devknx"
  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  install -Dm644 THIRD-PARTY-NOTICES.md \
    "$pkgdir/usr/share/licenses/$pkgname/THIRD-PARTY-NOTICES.md"
  install -Dm644 -t "$pkgdir/usr/share/licenses/$pkgname/" licenses/*
}}
''',
        encoding="utf-8",
    )
    return (formula, cask, binary, source)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--payload-dir", type=pathlib.Path, required=True)
    parser.add_argument("--output-dir", type=pathlib.Path, required=True)
    args = parser.parse_args()
    try:
        for path in generate(args.version, args.tag, args.payload_dir, args.output_dir):
            print(path)
    except (OSError, ValueError) as error:
        print(f"package_metadata: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
